Dev new report mode
lifebit-ai/pcgr-nf pull request #18
Opened 2021-07-23 11:33 UTC by cgpu

This PR introduces the changes for the combined table(?) ...

2021-08-05 17:55 UTC, imendes93 commented
[multiqc_report.html.zip](https://github.com/lifebit-ai/pcgr-nf/files/6940654/multiqc_report.html.zip)
This is an overview of the new report mode "summary". 
It features a summary plot, showing counts of variants by tiers; a summary table by gene and a summary table by variant. 

@Vlad-Dembrovskyi I suggest closing this PR and merging it into `dev`. The #17 should be integrated in a new PR. Let me know what you think. :)

2021-08-11 16:43 UTC, Vlad-Dembrovskyi requested changes
fails with nextflow version 20.01.0, needs debugging

2021-08-12 07:20 UTC, Vlad-Dembrovskyi requested changes

2021-08-12 07:20 UTC, Vlad-Dembrovskyi commented on main.nf
> +    file("combined.tiers.tsv") into combined_tiers_gene, combined_tiers_variant, combined_tiers_plot
```Suggestion
    file("combined.tiers.tsv") into (combined_tiers_gene, combined_tiers_variant, combined_tiers_plot)
```
This is to avoid nextflow crash on version 20.01.0. The way of inputing into multiple channels without brackets was probably introduced in later versions of nextflow.

With the suggested change pipeline stops crashing:
```
NXF_VER=20.01.0 nextflow run main.nf -profile docker,test --csv testdata/list-vcf-files-local.csv --max_cpus 4 --max_memory 14.GB -resume --report_mode report
```
![image](https://user-images.githubusercontent.com/64809705/129154662-b8b79089-2394-4e2a-89b3-20cea117a226.png)

2021-08-12 07:30 UTC, Vlad-Dembrovskyi commented
Regarding second issue I think it has to do with docker container `cimendes/lmas-python-base:0.2`. If I try to run just this container interactively with docker run command I get exactly this error that nextflow shows.
![image](https://user-images.githubusercontent.com/64809705/129155951-fab4022c-6836-4a8e-89d7-bf52c7794741.png)

This stack overflow may help:
https://stackoverflow.com/questions/58298774/standard-init-linux-go211-exec-user-process-caused-exec-format-error

2021-08-12 08:55 UTC, Vlad-Dembrovskyi commented
With local rebuild of container `quay.io/lifebitai/pcgr:python-base_1.0.0` it worked fine (also the bracket issue solved now)
![image](https://user-images.githubusercontent.com/64809705/129168590-7f88aea7-7861-4f3f-9189-dcd8b340ce71.png)

2021-08-12 10:11 UTC, imendes93 commented
I can't reproduce @Vlad-Dembrovskyi problem with the `quay.io/lifebitai/pcgr:python-base_1.0.0` container. That container was built on M1 and locally, i've no issues.  For reference, this container is used in the `pivot_table_gene`, `pivot_table_variant` and `plot_tiers` processes.
![image](https://user-images.githubusercontent.com/73831087/129179549-704a2244-67a2-4dd2-b38b-d57b0fa66b11.png)

A possible solution is to rebuild the container in another setup and see if that fixes @Vlad-Dembrovskyi's issue.

2021-08-12 11:40 UTC, Vlad-Dembrovskyi commented
With rebuilt container all works on my side. Pushed the re-built container to quay.io with same tag to overwrite previous container.
![image](https://user-images.githubusercontent.com/64809705/129190783-4b77ff8e-270d-4fa3-9456-3c826451da70.png)

2021-08-12 12:28 UTC, imendes93 commented
Locally the `plot_tiers` process fails for me but it ran successfully on clouldOS! So I'm pointing the cause of all our troubles to  mac silicon!

Here's the link to the public CloudOS run 
https://cloudos.lifebit.ai/app/jobs/611507e57db707019a054d47

2021-08-12 12:30 UTC, imendes93 commented
> fails with nextflow version 20.01.0, needs debugging

This has been fixed!

2021-08-12 12:40 UTC, Vlad-Dembrovskyi approved these changes
I see that cloudos job worked well with latest commit! Report is there, all tables look great! I think that concludes that PR is ready. Lets merge it to dev
![image](https://user-images.githubusercontent.com/64809705/129198145-12bfbf3f-1914-4c1d-a91b-a5a5eb6bb79b.png)
![image](https://user-images.githubusercontent.com/64809705/129198177-cae0f7d2-ec46-4be7-8062-955474c822b9.png)

2021-08-12 12:41 UTC, merged